In [1]:
import pandas as pd
import geocoder

In [2]:
df = pd.read_csv("terrorism.csv")
df.head()

       country  killed  wounded                region
0  Afghanistan    6119   6485.0                  Asia
1      Albania       0      0.0       Europe & Russia
2      Algeria       9      2.0  Africa & Middle East
3       Angola       0      0.0  Africa & Middle East
4    Argentina       0      2.0         South America

In [12]:
def geocode(country):
    g = geocoder.google(country, key='AIzaSyC9ATX-9ZQD5BoGff0mC6HU0hw7hUlKvN0')
    return pd.Series({
        'lat': g.lat,
        'lng': g.lng
    })

In [13]:
coords = df.country.apply(geocode)
coords

           lat         lng
0    33.939110   67.709953
1    41.153332   20.168331
2    28.033886    1.659626
3   -11.202692   17.873887
4   -38.416097  -63.616672
5    40.069099   45.038189
6   -25.274398  133.775136
7    47.516231   14.550072
8    40.143105   47.576927
9    26.066700   50.557700
10   23.684994   90.356331
11   50.503887    4.469936
12  -14.235004  -51.925280
13   42.733883   25.485830
14   12.238333   -1.561593
15   -3.373056   29.918886
16    7.369722   12.354722
17   56.130366 -106.346771
18    6.611111   20.939444
19   15.454166   18.732207
20  -35.675147  -71.542969
21   35.861660  104.195397
22    4.570868  -74.297333
23   35.126413   33.429859
24   49.817492   15.472962
25   -4.038333   21.758664
26   56.263920    9.501785
27   -1.831239  -78.183406
28   26.820553   30.802498
29    9.145000   40.489673
..         ...         ...
78   -0.228021   15.827659
79   61.524010  105.318756
80   -1.940278   29.873888
81   23.885942   45.079162
82    8.460555  -11.779889
83   48.669026   19.699024
84    5.152149   46.199616
85  -30.559482   22.937506
86   35.907757  127.766922
87    6.876992   31.306979
88   40.463667   -3.749220
89    7.873054   80.771797
90   12.862807   30.217636
91   60.128161   18.643501
92   46.818188    8.227512
93   34.802075   38.996815
94   23.697810  120.960515
95   38.861034   71.276093
96   -6.369028   34.888822
97   15.870032  100.992541
98   33.886917    9.537499
99   38.963745   35.243322
100   1.373333   32.290275
101  48.379433   31.165580
102  55.378051   -3.435973
103  37.090240  -95.712891
104 -32.522779  -55.765835
105   6.423750  -66.589730
106  14.493147  121.006893
107  15.552727   48.516388

[108 rows x 2 columns]

In [17]:
df.join(coords).to_csv("terrorism-coords.csv", index=False)